export const USER_FETCH_REQUESTED = 'USER_FETCH_REQUESTED';
export const USER_FETCH_SUCCEEDED = 'USER_FETCH_SUCCEEDED';
export const USER_FETCH_FAILED = 'USER_FETCH_FAILED';

export const TO_DO_FETCH_REQUESTED = 'TO_DO_FETCH_REQUESTED';
export const TO_DO_FETCH_SUCCEEDED = 'TO_DO_FETCH_SUCCEEDED';
export const TO_DO_FETCH_FAILED = 'TO_DO_FETCH_FAILED';
